# Specify a base image
# As we need a NodeJS to run the npm command, we can use the Node image with tag alpine, that means you will download the strict vers
# https://hub.docker.com/_/node?tab=description&page=1&ordering=last_updated
FROM node:alpine

# https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/learn/lecture/11436998#questions/14297316
USER node

# -p means to not print errors if exist and to create parent folder if neccessary
RUN mkdir -p /home/node/app

# Use this as working directory. Actually, new NodeJS forbids locating files in the root directory, so this command is neccessary
WORKDIR /home/node/app

# Copy only one file to the working folder in the container to make sure the next command will run from cashe if dockerfile for example will be changed
COPY --chown=node:node ./package.json ./

# Install some dependencies 
RUN npm install

# Copy all files from current folder to the working folder in the container
COPY --chown=node:node ./ ./


# Default command
CMD ["npm", "run", "start"]